window.NEXA_REAL_PROPERTIES = [
  {
    id: "local-rodolfo",
    name: "Local Rodolfo",
    type: "Local comercial",
    category: "locales",
    location: "Centro de Pamplona, Norte de Santander",
    status: "disponible",
    statusLabel: "EN COMERCIALIZACIÓN",
    price: "Valor por confirmar",
    image: "../assets/images/properties/local-rodolfo.jpg",
    cardImage: "assets/images/properties/local-rodolfo.jpg",
    video: "https://nexa-inmobiliaria-api.vercel.app/api/v1/public/media/local-rodolfo.mp4",
    summary: "Inmueble comercial documentado con recorrido aéreo y visuales de su entorno urbano.",
    description: "El material disponible muestra la ubicación céntrica del inmueble, su fachada sobre vía urbana y la relación directa con el centro tradicional de Pamplona. Los datos de área, distribución interior y valor comercial están pendientes de confirmación.",
    specs: ["Ubicación céntrica", "Fachada urbana", "Recorrido en video"],
    details: [
      ["Tipo", "Local comercial"],
      ["Sector", "Centro de Pamplona"],
      ["Área", "Por confirmar"],
      ["Valor", "Por confirmar"],
    ],
  },
  {
    id: "lote-san-sebastian",
    name: "Lote esquinero en San Sebastián",
    type: "Lote",
    category: "lotes",
    location: "San Sebastián, Pamplona",
    status: "disponible",
    statusLabel: "DISPONIBLE",
    price: "Valor por confirmar",
    image: "../assets/images/properties/lote-san-sebastian.jpg",
    cardImage: "assets/images/properties/lote-san-sebastian.jpg",
    video: "https://nexa-inmobiliaria-api.vercel.app/api/v1/public/media/lote-san-sebastian.mp4",
    summary: "Lote esquinero de 7 × 14 metros dentro del conjunto residencial San Sebastián.",
    description: "Una opción residencial en un entorno tranquilo y rodeado de montaña. Su condición esquinera favorece la iluminación y abre posibilidades para diseñar una vivienda familiar adaptada al terreno.",
    specs: ["98 m²", "7 × 14 m", "Lote esquinero"],
    details: [
      ["Área", "98 m²"],
      ["Dimensiones", "7 × 14 m"],
      ["Ubicación", "San Sebastián"],
      ["Condición", "Esquinero"],
    ],
  },
  {
    id: "altos-san-sebastian",
    name: "Altos de San Sebastián",
    type: "Proyecto residencial",
    category: "proyectos",
    location: "San Sebastián, Pamplona",
    status: "en-desarrollo",
    statusLabel: "EN DESARROLLO",
    price: "Valor por confirmar",
    image: "../assets/images/properties/altos-san-sebastian.jpg",
    cardImage: "assets/images/properties/altos-san-sebastian.jpg",
    video: "https://nexa-inmobiliaria-api.vercel.app/api/v1/public/media/altos-san-sebastian.mp4",
    summary: "Proyecto residencial con vistas abiertas hacia Pamplona y registro audiovisual de su avance.",
    description: "El contenido de obra documenta apartamentos, parqueadero, diferentes niveles del edificio y material específico de la unidad 501. Las áreas, precios y disponibilidad definitiva deben confirmarse directamente con el asesor.",
    specs: ["Apartamentos", "Parqueadero", "Vista panorámica"],
    details: [
      ["Tipo", "Proyecto residencial"],
      ["Material disponible", "Obra y unidad 501"],
      ["Parqueadero", "Documentado"],
      ["Disponibilidad", "Por confirmar"],
    ],
  },
  {
    id: "edificio-yarumo",
    name: "Edificio Yarumo",
    type: "Proyecto de apartamentos",
    category: "proyectos",
    location: "Pamplona, Norte de Santander",
    status: "en-desarrollo",
    statusLabel: "PROYECTO RESIDENCIAL",
    price: "Valor por confirmar",
    image: "../assets/images/properties/edificio-yarumo.jpg",
    cardImage: "assets/images/properties/edificio-yarumo.jpg",
    video: "https://nexa-inmobiliaria-api.vercel.app/api/v1/public/media/edificio-yarumo.mp4",
    summary: "Proyecto de apartamentos presentado mediante fachada, distribución arquitectónica y recorrido visual.",
    description: "La visualización disponible presenta una propuesta residencial con tres habitaciones, dos baños, sala, comedor, cocina y parqueadero. Las áreas totales, precios y fechas de entrega se mantienen por confirmar.",
    specs: ["3 habitaciones", "2 baños", "Parqueadero"],
    details: [
      ["Habitaciones", "3"],
      ["Baños", "2"],
      ["Parqueadero", "Incluido en la visualización"],
      ["Área total", "Por confirmar"],
    ],
  },
];

window.NexaRealProperties = {
  getAll() {
    return window.NEXA_REAL_PROPERTIES;
  },
  getById(id) {
    return window.NEXA_REAL_PROPERTIES.find((property) => property.id === id) || null;
  },
};
